import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/provider/ThemeProvider";
import { Cairo } from "next/font/google"
import { cn } from "@/lib/utils";


const font = Cairo({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900', '1000']
})

export const metadata: Metadata = {
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/favicon.ico?v=4']
  },
  title: "MOHAMMED",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={cn(font.className)}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
